#!/bin/bash
cd myworkspace-repo/
rm -rf node_modules
rm -rf bower_components
npm install --allow-root
npm install -g bower
bower install --allow-root
npm install -g gulp-cli --allow-root
npm install -g gulp --allow-root
curl gulp
