groups:
 - name: main
   jobs:
#     - Run_Tests
     - Publish_Job

resources:
- name: myworkspace-repo
  type: git
  source:
     uri: https://github.com/buggavep/sample_npm_build.git
     trigger: true
     branch: master

- name: myworkspace-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-hub-image-myworkspace}}

jobs: 
 #- name: Run_Tests
 #  plan: 
 #  - get: myworkspace-repo 
 #    trigger: true 
 #  - task: build
 #    file: myworkspace-repo/ci/tasks/build.yml   

 - name: Publish
   serial: true
   public: true
   plan:
   - get: myworkspace-repo
     trigger: true
   - put: myworkspace-image
     params:
       build: myworkspace-repo/
