resources:
- name: myworkspace-repo
  type: git
  source:
     uri: https://github.com/heroku/node-js-sample.git
     #uri: https://github.com/buggavep/node-js-sample.git   
     trigger: true
     branch: master

jobs:
- name: integration
  plan:
  - get: myworkspace-repo
    trigger: true

  - task: npm-install
    config:  
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: node, tag: "6" }
      inputs:
        - name: myworkspace-repo
          path: myworkspace/app.js
      outputs:
        - name: node_modules
      run:
        path: npm
        args: [ install ]


  - task: npm-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: node, tag: "6" }
      inputs:
        - name: myworkspace-repo
          path: myworkspace/app.js
        - name: node_modules
      run:
        path: npm
        args: [ test ]
     # run:
        #path: myworkspace-repo/node-js-sample/install.sh
     #   path: ./install.sh
        #path: echo
        #args: ["Hello World!"]
    
   
