resources:
- name: myworkspace-repo
  type: git
  source:
     #uri: https://github.com/heroku/node-js-sample.git
     #uri: https://github.com/buggavep/node-js-sample.git   
     #uri: https://github.com/buggavep/gulp_concourse_project.git
     uri: https://github.com/jairtrejo/simple-gulp-template.git
     trigger: true
     branch: master

jobs:
- name: integration
  plan:
  - get: myworkspace-repo
    trigger: true

  - task: npm-install
    config:  
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: node, tag: "5" }
      inputs:
        - name: myworkspace-repo
          path: myworkspace-repo/
      outputs:
        - name: node_modules
        - name: bower_components
      run:
        path: sh
        args: 
          - -exec
          - | 
            cd myworkspace-repo/
            npm install 
            npm install -g bower
            bower install --allow-root
            npm install -g gulp
            curl gulp
    
   
