groups:
 - name: main
   jobs:
#     - Run_Tests
     - Versioning_job
     - Publish_job

resources:
- name: myworkspace-repo
  type: git
  source:
     uri: {{git-url}}
     trigger: true
     branch: master

- name: resource-version
  type: semver
  source:
    driver: git
    initial_version: 0.0.1
    uri: {{git-uri-bump-semver}}
    branch: version
    file: version
    #private_key: {{github-private-key}}

- name: myworkspace-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-hub-image-myworkspace}}

jobs: 
 #- name: Run_Tests
 #  plan: 
 #  - get: myworkspace-repo 
 #    trigger: true 
 #  - task: build
 #    file: myworkspace-repo/ci/tasks/build.yml   

 - name: Versioning_job 
   public: true
   serial: true
   plan:
   - get: resource-version
   - task: display-version
     file: myworkspace-repo/ci/tasks/resource.yml
 
 - name: Publish_job
   serial: true
   public: true
   plan:
   - get: myworkspace-repo
   - put: myworkspace-image
     params:
       build: myworkspace-repo/
