resources:
- name: myworkspace-repo
  type: git
  source:
     uri: https://github.com/buggavep/gulp_concourse_project.git
     #uri: https://github.com/jairtrejo/simple-gulp-template.git
     trigger: true
     branch: master

- name: deploy-test
  type: cf
  source: 
   api: https://api.run.pivotal.io
   username: {{cf-user}}
   password: {{cf-password}}
   organization: {{cf-org}}
   space: {{cf-space}}  
   skip_cert_chek: false

jobs:
- name: integration
  plan:
  - get: myworkspace-repo
    trigger: true
  - task: Build
    config:  
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: node, tag: "5" }

      inputs:
        - name: myworkspace-repo
          path: myworkspace-repo/

      outputs:
        - name: node_modules
        - name: bower_components

      run:
        path: sh
        args: 
          - -exec
          - | 
            cd myworkspace-repo/
            rm -rf node_modules
            rm -rf bower_components
            npm install --allow-root
            npm install -g bower
            bower install --allow-root
            npm install -g gulp-cli --allow-root
            npm install -g gulp --allow-root 
            curl gulp 

   - put:  deploy-test
     params:
        manifest: myworkspace-repo/ci/manifest.yml
