groups:
 - name: main
   jobs:
     - build
     - package

resources:
- name: myworkspace-repo
  type: git
  source:
     uri: https://github.com/buggavep/sample_npm_build.git
     trigger: true
     branch: master

jobs: 
 - name: build
   plan: 
   - get: myworkspace-repo 
     trigger: true 
   - task: build
     file: myworkspace-repo/ci/tasks/build.yml   

 - name: package
   plan:
   - get: myworkspace-repo
     passed: [build]
     trigger: true
   - task: package
     file: myworkspace-repo/ci/tasks/package.yml
