resources:
- name: myworkspace-repo
  type: git
  source:
     uri: https://github.com/heroku/node-js-sample.git
     branch: master

jobs:
- name: integration
  plan:
  - get: myworkspace-repo
    trigger: true
  - task: build-npm
    config  
      platform: linux
      image_resource:
        type: docker-image
        source:{repository: busybox}
      inputs:
      - name: myworkspace-repo
      run:
        paths:
        - '/myworkspace-repo/scripts/install.sh'
  

