groups:
 - name: main
   jobs:
     - build
     - package

resources:
- name: myworkspace-repo
  type: git
  source:
     uri: https://github.com/buggavep/sample_npm_build.git
     trigger: true
     branch: master

jobs: 
 - name: build
   plan: 
   - get: myworkspace-repo 
     trigger: true 
   - task: build
     file: myworkspace-repo/ci/tasks/build.yml   

 - name: package
   public: true
   serial: true
   plan:
   - get: myworkspace-repo
     trigger: true
     passed: 
        - build
   - put: myworkspace-image
     params: 
       build: myworkspace-repo/ci/tasks/docker   
   #- task: package
   #  file: myworkspace-repo/ci/tasks/package.yml

 - name: myworkspace-image
   type: docker-image
   source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-hub-image-myworkspace}}
