groups:
 - name: main
   jobs:
     - Run_Tests
#     - Versioning_job
     - Publish_job

resources:
- name: myworkspace-repo
  type: git
  source:
     uri: {{git-url}}
     trigger: true
     branch: master

- name: myworkspace-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-hub-image-myworkspace}}

jobs: 
 - name: Run_Tests
   plan: 
   - get: myworkspace-repo 
     trigger: true 
   - task: build
     file: myworkspace-repo/ci/tasks/build.yml   
 
 - name: Publish_job
   serial: true
   public: true
   plan:
   - get: myworkspace-repo
     trigger: true
     passed: [Run_Tests]
   - put: myworkspace-image
     params:
       build: myworkspace-repo/
