groups:
 - name: main
   jobs:
     - build
     - package

resources:
- name: myworkspace-repo
  type: git
  source:
     uri: https://github.com/buggavep/sample_npm_build.git
     trigger: true
     branch: master

jobs: 
 - name: build
   plan: 
   - get: myworkspace-repo 
     trigger: true 
   - task: build
     file: myworkspace-repo/ci/tasks/build.yml   

# - name: package
#   plan:
#   - get: myworkspace-repo
#     trigger: true

#   - task: package
#     file: myworkspace-repo/ci/tasks/package.yml
 
- name: package
  public: true
  serial: true
  plan:
  - get: resource-tutorial
#  - put: hello-world-docker-image
  params:
      build: myworkspace-repo/ci/docker
