resources:
- name: myworkspace-repo
  type: git
  source:
     #uri: https://github.com/heroku/node-js-sample.git
     uri: https://github.com/buggavep/node-js-sample.git   
     branch: master

jobs:
- name: integration
  plan:
  - get: myworkspace-repo
    trigger: true

  - task: build-npm
    config:  
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: node}
      inputs:
      - name: myworkspace-repo
      run:
        path: myworkspace-repo/ci/install.sh
        #path: echo
        #args: ["Hello World!"]
