---
resources:
  - name: myworkspace-repo
    type: git
    source:
      uri: #yet to decide
      branch: develop

jobs:
 - name: integration
   serial: true

   plan:
   - {get: myworkspace-repo, trigger: true}
   - task: build-npm

   config:
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: node

    inputs:
     - name: myworkspace-repo
    
    run: 
     path: myworkspace-repo/scripts/install.sh
