groups:
 - name: main
   jobs:
     - build
     - package

resources:
- name: myworkspace-repo
  type: git
  source:
     uri: https://github.com/buggavep/sample_npm_build.git
     trigger: true
     branch: master

- name: myworkspace-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-hub-image-myworkspace}}

jobs: 
 - name: build
   plan: 
   - get: myworkspace-repo 
     trigger: true 
   - task: build
     file: myworkspace-repo/ci/tasks/build.yml   

 - name: package
   serial: true
   public: true
   plan:
   - get: myworkspace-repo
     trigger: true
     passed: 
         -build
   - put: myworkspace-image 
   - task: deploy 
     file: myworkspace-repo/ci/tasks/package.yml
