resources:
- name: myworkspace-repo
  type: git
  source:
     #uri: https://github.com/heroku/node-js-sample.git
     #uri: https://github.com/buggavep/node-js-sample.git   
     uri: https://github.com/buggavep/gulp_concourse_project.git
     trigger: true
     branch: master

jobs:
- name: integration
  plan:
  - get: myworkspace-repo
    trigger: true

  - task: npm-install
    config:  
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: node, tag: "6" }
      inputs:
        - name: myworkspace-repo
          path: myworkspace-repo/
      outputs:
        - name: node_modules
      run:
        path: sh
        args: 
          - -exec
          - | 
            cd myworkspace-repo
            npm install -g bower
            npm install gulp
            gulp
        #dir: "myworkspace-repo"
        #args: [ install ]
        #args: [npm install npm ]

#  - task: bower-install
#    config:
#      platform: linux
#      image_resource:
#        type: docker-image
#        source: {repository: node, tag: "6" }
#      inputs:
#        - name: myworkspace-repo
#          path: myworkspace-repo/
#        - name: node_modules
#      run:
#        path: bower
#        args: [ install ]
#     
#     # run:
#        #path: myworkspace-repo/node-js-sample/install.sh
#     #   path: ./install.sh
#        #path: echo
#        #args: ["Hello World!"]
    
   
